name: pos_desktop_loop
description: "A POS Desktop Application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  syncfusion_flutter_charts: ^29.2.4
  path_provider: ^2.1.5
  file_picker: ^10.2.0
  excel: ^4.0.6
  share_plus: ^11.0.0
  provider: ^6.1.5
  rename: ^3.1.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.0
  print_bluetooth_thermal: ^1.1.6
  intl: ^0.20.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/finance.png
    - assets/images/giving.png
    - assets/images/
    - assets/fonts/
    - assets/animations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          # style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          # style: bold  
